repo: "js-heart-css"
canvasCourse: "467503"
canvasAssignment: "4202550"

naming: true
commits: 1

html:
  - path: "index.html"
    locked: true

css:
  - path: "css/main.css"
    locked: true

js:
  - path: "js/main.js"
    valid: true
    bestPractices: true
    search:
      - 'addClass\('
      - 'removeClass\('
      - 'show\('


